Bootstrap: add support for kubeconfig file for source and target cluster
admiraltyio/multicluster-service-account pull request #9
Opened 2019-09-16 12:18 UTC by asaintsever

Goal of this PR is to allow to provide kubeconfig file for both source and target clusters (this is as an option). 
It is particularly useful for the source cluster as its context may not be part of the local kube config file.

2019-09-18 23:03 UTC, adrienjt requested changes
Thank you for submitting this PR. As you saw, this was a TODO comment. :smiley:

2019-09-18 23:03 UTC, adrienjt commented on cmd/kubemcsa/main.go
> +	srcK8SConfig = bootstrapCmd.Flag("source-kubeconfig", "(default: current kubeconfig file) kubeconfig file to use for source cluster").ExistingFile()
I know this would be breaking, but I would now make contexts optional, using flags. The breaking aspect is okay in my opinion, as this tool is still a v0.x.

Note also the updated help strings, which are made consistent around the concepts of source and target clusters.

```go
var (
	bootstrapCmd = kingpin.Command("bootstrap", "Allow service account import controller in a target cluster to import service accounts from a source cluster.")
	dstCtx       = bootstrapCmd.Flag("target-context", "(default: current context) name of the kubeconfig context to use for the target cluster").String()
	srcCtx       = bootstrapCmd.Flag("source-context", "(default: current context) name of the kubeconfig context to use for the source cluster").String()
	dstK8sConfig = bootstrapCmd.Flag("target-kubeconfig", "(default: KUBECONFIG environment variable or ~/.kube/config) path to kubeconfig file to use for the target cluster").ExistingFile()
	srcK8sConfig = bootstrapCmd.Flag("source-kubeconfig", "(default: KUBECONFIG environment variable or ~/.kube/config) path to kubeconfig file to use for the source cluster").ExistingFile()
)
```

2019-09-18 23:03 UTC, adrienjt commented on pkg/bootstrap/bootstrap.go
> +	srcCfg, _, err := config.NamedConfigAndNamespace(srcKubeconfig, srcCtx)
I'd rather not modify the `config` package as part of this PR, because we don't need the SAI->kubeconfig fallback mechanism nor the namespace output that the `config` package provides. Instead, we can use the `clientcmd` package directly:

```go
rules := clientcmd.NewDefaultClientConfigLoadingRules()
rules.ExplicitPath = srcKubeconfig // if empty, env var or default path will be used instead
overrides := &clientcmd.ConfigOverrides{CurrentContext: srcCtx} // if srcCtx is empty, kubeconfig's current context will be used instead
srcCfg, err := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(rules, overrides).ClientConfig()
// ...
```
(same for dstCfg)

2019-09-19 08:48 UTC, asaintsever commented on pkg/bootstrap/bootstrap.go
> +	srcCfg, _, err := config.NamedConfigAndNamespace(srcKubeconfig, srcCtx)
Right, in fact the namespace returned from `config.NamedConfigAndNamespace` was not used for bootstrapping. So yes we can make things simpler by directly calling `clientcmd`.

2019-09-19 09:05 UTC, asaintsever commented on cmd/kubemcsa/main.go
> +	srcK8SConfig = bootstrapCmd.Flag("source-kubeconfig", "(default: current kubeconfig file) kubeconfig file to use for source cluster").ExistingFile()
Done

2019-09-20 00:36 UTC, adrienjt approved these changes

2019-09-20 00:37 UTC, merged